embed_assets: on

javascripts:
  common:
    - public/javascripts/application.js
    - public/javascripts/project.js
  lib:
    - public/javascripts/lib/jquery.js
    - public/javascripts/lib/jquery.flot.js
    - public/javascripts/lib/jquery-ui.js

stylesheets:
  common:
    - public/stylesheets/application.css
    - public/stylesheets/projects.css
    - public/stylesheets/updates.css
  lib:
    - public/stylesheets/lib/jquery-ui.css
