embed_assets: on

javascripts:
  common:
    - public/javascripts/application.js
  lib:
    - public/javascripts/lib/jquery.js
    - public/javascripts/lib/jquery.flot.js

stylesheets:
  common:
    - public/stylesheets/application.css
    - public/stylesheets/projects.css
